/*   -*- buffer-read-only: t -*- vi: set ro:
 *  
 *  DO NOT EDIT THIS FILE   (danetool-args.c)
 *  
 *  It has been AutoGen-ed  March 22, 2013 at 07:34:31 PM by AutoGen 5.16
 *  From the definitions    danetool-args.def
 *  and the template file   options
 *
 * Generated from AutoOpts 36:4:11 templates.
 *
 *  AutoOpts is a copyrighted work.  This source file is not encumbered
 *  by AutoOpts licensing, but is provided under the licensing terms chosen
 *  by the danetool author or copyright holder.  AutoOpts is
 *  licensed under the terms of the LGPL.  The redistributable library
 *  (``libopts'') is licensed under the terms of either the LGPL or, at the
 *  users discretion, the BSD license.  See the AutoOpts and/or libopts sources
 *  for details.
 *
 * The danetool program is copyrighted and licensed
 * under the following terms:
 *
 *  Copyright (C) 2000-2012 Free Software Foundation, all rights reserved.
 *  This is free software. It is licensed for use, modification and
 *  redistribution under the terms of the
 *  GNU General Public License, version 3 or later
 *      <http://gnu.org/licenses/gpl.html>
 *
 *  danetool is free software: you can redistribute it and/or modify it
 *  under the terms of the GNU General Public License as published by the
 *  Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *  
 *  danetool is distributed in the hope that it will be useful, but
 *  WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *  See the GNU General Public License for more details.
 *  
 *  You should have received a copy of the GNU General Public License along
 *  with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef __doxygen__
#define OPTION_CODE_COMPILE 1
#include "danetool-args.h"
#include <sys/types.h>

#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <errno.h>

#ifdef  __cplusplus
extern "C" {
#endif
extern FILE * option_usage_fp;

/* TRANSLATORS: choose the translation for option names wisely because you
                cannot ever change your mind. */
#define zCopyright      (danetool_opt_strs+0)
#define zLicenseDescrip (danetool_opt_strs+276)


#ifndef NULL
#  define NULL 0
#endif

/*
 *  danetool option static const strings
 */
static char const danetool_opt_strs[2511] =
/*     0 */ "danetool 3.1.10\n"
            "Copyright (C) 2000-2012 Free Software Foundation, all rights reserved.\n"
            "This is free software. It is licensed for use, modification and\n"
            "redistribution under the terms of the\n"
            "GNU General Public License, version 3 or later\n"
            "    <http://gnu.org/licenses/gpl.html>\n\0"
/*   276 */ "danetool is free software: you can redistribute it and/or modify it under\n"
            "the terms of the GNU General Public License as published by the Free\n"
            "Software Foundation, either version 3 of the License, or (at your option)\n"
            "any later version.\n\n"
            "danetool is distributed in the hope that it will be useful, but WITHOUT ANY\n"
            "WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS\n"
            "FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more\n"
            "details.\n\n"
            "You should have received a copy of the GNU General Public License along\n"
            "with this program.  If not, see <http://www.gnu.org/licenses/>.\n\0"
/*   881 */ "Enable debugging.\0"
/*   899 */ "DEBUG\0"
/*   905 */ "debug\0"
/*   911 */ "More verbose output\0"
/*   931 */ "VERBOSE\0"
/*   939 */ "verbose\0"
/*   947 */ "Input file\0"
/*   958 */ "INFILE\0"
/*   965 */ "infile\0"
/*   972 */ "Output file\0"
/*   984 */ "OUTFILE\0"
/*   992 */ "outfile\0"
/*  1000 */ "Loads a public key file\0"
/*  1024 */ "LOAD_PUBKEY\0"
/*  1036 */ "load-pubkey\0"
/*  1048 */ "Loads a certificate file\0"
/*  1073 */ "LOAD_CERTIFICATE\0"
/*  1090 */ "load-certificate\0"
/*  1107 */ "Sets a DLV file\0"
/*  1123 */ "DLV\0"
/*  1127 */ "dlv\0"
/*  1131 */ "Hash algorithm to use for signing.\0"
/*  1166 */ "HASH\0"
/*  1171 */ "hash\0"
/*  1176 */ "Check a host's DANE TLSA entry.\0"
/*  1208 */ "CHECK\0"
/*  1214 */ "check\0"
/*  1220 */ "Check only the end-entity's certificate.\0"
/*  1261 */ "CHECK_EE\0"
/*  1270 */ "check-ee\0"
/*  1279 */ "Check only the CA's certificate.\0"
/*  1312 */ "CHECK_CA\0"
/*  1321 */ "check-ca\0"
/*  1330 */ "Do not verify any DNSSEC signature.\0"
/*  1366 */ "INSECURE\0"
/*  1375 */ "insecure\0"
/*  1384 */ "Use the local DNS server for DNSSEC resolving.\0"
/*  1431 */ "LOCAL_DNS\0"
/*  1441 */ "no-local-dns\0"
/*  1454 */ "no\0"
/*  1457 */ "Use DER format for input certificates and private keys.\0"
/*  1513 */ "INDER\0"
/*  1519 */ "no-inder\0"
/*  1528 */ "This is an alias for 'inder'\0"
/*  1557 */ "inraw\0"
/*  1563 */ "Print the DANE RR data on a certificate or public key\0"
/*  1617 */ "TLSA_RR\0"
/*  1625 */ "tlsa-rr\0"
/*  1633 */ "Specify the hostname to be used in the DANE RR\0"
/*  1680 */ "HOST\0"
/*  1685 */ "host\0"
/*  1690 */ "The protocol set for DANE data (tcp, udp etc.)\0"
/*  1737 */ "PROTO\0"
/*  1743 */ "proto\0"
/*  1749 */ "Specify the port number for the DANE data.\0"
/*  1792 */ "PORT\0"
/*  1797 */ "port\0"
/*  1802 */ "Whether the provided certificate or public key is a Certificate\n"
            "Authority.\0"
/*  1877 */ "CA\0"
/*  1880 */ "ca\0"
/*  1883 */ "Use the hash of the X.509 certificate, rather than the public key.\0"
/*  1950 */ "X509\0"
/*  1955 */ "x509\0"
/*  1960 */ "This is an alias for 'domain'\0"
/*  1990 */ "local\0"
/*  1996 */ "The provided certificate or public key is issued by the local domain.\0"
/*  2066 */ "DOMAIN\0"
/*  2073 */ "no-domain\0"
/*  2083 */ "Display extended usage information and exit\0"
/*  2127 */ "help\0"
/*  2132 */ "Extended usage information passed thru pager\0"
/*  2177 */ "more-help\0"
/*  2187 */ "Output version information and exit\0"
/*  2223 */ "version\0"
/*  2231 */ "DANETOOL\0"
/*  2240 */ "danetool - GnuTLS DANE tool - Ver. 3.1.10\n"
            "USAGE:  %s [ -<flag> [<val>] | --<name>[{=| }<val>] ]...\n\0"
/*  2340 */ "bug-gnutls@gnu.org\0"
/*  2359 */ "\n\n\0"
/*  2362 */ "\n"
            "Tool to generate and check DNS resource records for the DANE protocol.\n\0"
/*  2435 */ "danetool 3.1.10\0"
/*  2451 */ "danetool [options]\n"
            "danetool --help for usage instructions.\n";

/*
 *  debug option description:
 */
#define DEBUG_DESC      (danetool_opt_strs+881)
#define DEBUG_NAME      (danetool_opt_strs+899)
#define DEBUG_name      (danetool_opt_strs+905)
#define DEBUG_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_NUMERIC))

/*
 *  verbose option description:
 */
#define VERBOSE_DESC      (danetool_opt_strs+911)
#define VERBOSE_NAME      (danetool_opt_strs+931)
#define VERBOSE_name      (danetool_opt_strs+939)
#define VERBOSE_FLAGS     (OPTST_DISABLED)

/*
 *  infile option description:
 */
#define INFILE_DESC      (danetool_opt_strs+947)
#define INFILE_NAME      (danetool_opt_strs+958)
#define INFILE_name      (danetool_opt_strs+965)
#define INFILE_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_FILE))

/*
 *  outfile option description:
 */
#define OUTFILE_DESC      (danetool_opt_strs+972)
#define OUTFILE_NAME      (danetool_opt_strs+984)
#define OUTFILE_name      (danetool_opt_strs+992)
#define OUTFILE_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  load-pubkey option description:
 */
#define LOAD_PUBKEY_DESC      (danetool_opt_strs+1000)
#define LOAD_PUBKEY_NAME      (danetool_opt_strs+1024)
#define LOAD_PUBKEY_name      (danetool_opt_strs+1036)
#define LOAD_PUBKEY_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  load-certificate option description:
 */
#define LOAD_CERTIFICATE_DESC      (danetool_opt_strs+1048)
#define LOAD_CERTIFICATE_NAME      (danetool_opt_strs+1073)
#define LOAD_CERTIFICATE_name      (danetool_opt_strs+1090)
#define LOAD_CERTIFICATE_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  dlv option description:
 */
#define DLV_DESC      (danetool_opt_strs+1107)
#define DLV_NAME      (danetool_opt_strs+1123)
#define DLV_name      (danetool_opt_strs+1127)
#define DLV_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  hash option description:
 */
#define HASH_DESC      (danetool_opt_strs+1131)
#define HASH_NAME      (danetool_opt_strs+1166)
#define HASH_name      (danetool_opt_strs+1171)
#define HASH_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  check option description:
 */
#define CHECK_DESC      (danetool_opt_strs+1176)
#define CHECK_NAME      (danetool_opt_strs+1208)
#define CHECK_name      (danetool_opt_strs+1214)
#define CHECK_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  check-ee option description:
 */
#define CHECK_EE_DESC      (danetool_opt_strs+1220)
#define CHECK_EE_NAME      (danetool_opt_strs+1261)
#define CHECK_EE_name      (danetool_opt_strs+1270)
#define CHECK_EE_FLAGS     (OPTST_DISABLED)

/*
 *  check-ca option description:
 */
#define CHECK_CA_DESC      (danetool_opt_strs+1279)
#define CHECK_CA_NAME      (danetool_opt_strs+1312)
#define CHECK_CA_name      (danetool_opt_strs+1321)
#define CHECK_CA_FLAGS     (OPTST_DISABLED)

/*
 *  insecure option description:
 */
#define INSECURE_DESC      (danetool_opt_strs+1330)
#define INSECURE_NAME      (danetool_opt_strs+1366)
#define INSECURE_name      (danetool_opt_strs+1375)
#define INSECURE_FLAGS     (OPTST_DISABLED)

/*
 *  local-dns option description:
 */
#define LOCAL_DNS_DESC      (danetool_opt_strs+1384)
#define LOCAL_DNS_NAME      (danetool_opt_strs+1431)
#define NOT_LOCAL_DNS_name  (danetool_opt_strs+1441)
#define NOT_LOCAL_DNS_PFX   (danetool_opt_strs+1454)
#define LOCAL_DNS_name      (NOT_LOCAL_DNS_name + 3)
#define LOCAL_DNS_FLAGS     (OPTST_DISABLED)

/*
 *  inder option description:
 */
#define INDER_DESC      (danetool_opt_strs+1457)
#define INDER_NAME      (danetool_opt_strs+1513)
#define NOT_INDER_name  (danetool_opt_strs+1519)
#define NOT_INDER_PFX   (danetool_opt_strs+1454)
#define INDER_name      (NOT_INDER_name + 3)
#define INDER_FLAGS     (OPTST_DISABLED)

/*
 *  inraw option description:
 */
#define INRAW_DESC    (danetool_opt_strs+1528)
#define INRAW_NAME    NULL
#define INRAW_name    (danetool_opt_strs+1557)
#define INRAW_FLAGS     (INDER_FLAGS | OPTST_ALIAS)

/*
 *  tlsa-rr option description with
 *  "Must also have options" and "Incompatible options":
 */
#define TLSA_RR_DESC      (danetool_opt_strs+1563)
#define TLSA_RR_NAME      (danetool_opt_strs+1617)
#define TLSA_RR_name      (danetool_opt_strs+1625)
static int const aTlsa_RrMustList[] = {
    INDEX_OPT_HOST, NO_EQUIVALENT };
#define TLSA_RR_FLAGS     (OPTST_DISABLED)

/*
 *  host option description:
 */
#define HOST_DESC      (danetool_opt_strs+1633)
#define HOST_NAME      (danetool_opt_strs+1680)
#define HOST_name      (danetool_opt_strs+1685)
#define HOST_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  proto option description:
 */
#define PROTO_DESC      (danetool_opt_strs+1690)
#define PROTO_NAME      (danetool_opt_strs+1737)
#define PROTO_name      (danetool_opt_strs+1743)
#define PROTO_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  port option description:
 */
#define PORT_DESC      (danetool_opt_strs+1749)
#define PORT_NAME      (danetool_opt_strs+1792)
#define PORT_name      (danetool_opt_strs+1797)
#define PORT_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_NUMERIC))

/*
 *  ca option description:
 */
#define CA_DESC      (danetool_opt_strs+1802)
#define CA_NAME      (danetool_opt_strs+1877)
#define CA_name      (danetool_opt_strs+1880)
#define CA_FLAGS     (OPTST_DISABLED)

/*
 *  x509 option description:
 */
#define X509_DESC      (danetool_opt_strs+1883)
#define X509_NAME      (danetool_opt_strs+1950)
#define X509_name      (danetool_opt_strs+1955)
#define X509_FLAGS     (OPTST_DISABLED)

/*
 *  local option description:
 */
#define LOCAL_DESC    (danetool_opt_strs+1960)
#define LOCAL_NAME    NULL
#define LOCAL_name    (danetool_opt_strs+1990)
#define LOCAL_FLAGS     (DOMAIN_FLAGS | OPTST_ALIAS)

/*
 *  domain option description:
 */
#define DOMAIN_DESC      (danetool_opt_strs+1996)
#define DOMAIN_NAME      (danetool_opt_strs+2066)
#define NOT_DOMAIN_name  (danetool_opt_strs+2073)
#define NOT_DOMAIN_PFX   (danetool_opt_strs+1454)
#define DOMAIN_name      (NOT_DOMAIN_name + 3)
#define DOMAIN_FLAGS     (OPTST_INITENABLED)

/*
 *  Help/More_Help/Version option descriptions:
 */
#define HELP_DESC       (danetool_opt_strs+2083)
#define HELP_name       (danetool_opt_strs+2127)
#ifdef HAVE_WORKING_FORK
#define MORE_HELP_DESC  (danetool_opt_strs+2132)
#define MORE_HELP_name  (danetool_opt_strs+2177)
#define MORE_HELP_FLAGS (OPTST_IMM | OPTST_NO_INIT)
#else
#define MORE_HELP_DESC  NULL
#define MORE_HELP_name  NULL
#define MORE_HELP_FLAGS (OPTST_OMITTED | OPTST_NO_INIT)
#endif
#ifdef NO_OPTIONAL_OPT_ARGS
#  define VER_FLAGS     (OPTST_IMM | OPTST_NO_INIT)
#else
#  define VER_FLAGS     (OPTST_SET_ARGTYPE(OPARG_TYPE_STRING) | \
                         OPTST_ARG_OPTIONAL | OPTST_IMM | OPTST_NO_INIT)
#endif
#define VER_DESC        (danetool_opt_strs+2187)
#define VER_name        (danetool_opt_strs+2223)
/*
 *  Declare option callback procedures
 */
extern tOptProc
    optionBooleanVal,   optionNestedVal,    optionNumericVal,
    optionPagedUsage,   optionPrintVersion, optionResetOpt,
    optionStackArg,     optionTimeDate,     optionTimeVal,
    optionUnstackArg,   optionVendorOption;
static tOptProc
    doOptDebug, doOptInfile, doOptInraw, doOptLocal, doUsageOpt;
#define VER_PROC        optionPrintVersion

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/**
 *  Define the danetool Option Descriptions.
 * This is an array of OPTION_CT entries, one for each
 * option that the danetool program responds to.
 */
static tOptDesc optDesc[OPTION_CT] = {
  {  /* entry idx, value */ 0, VALUE_OPT_DEBUG,
     /* equiv idx, value */ 0, VALUE_OPT_DEBUG,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ DEBUG_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --debug */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptDebug,
     /* desc, NAME, name */ DEBUG_DESC, DEBUG_NAME, DEBUG_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 1, VALUE_OPT_VERBOSE,
     /* equiv idx, value */ 1, VALUE_OPT_VERBOSE,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, NOLIMIT, 0,
     /* opt state flags  */ VERBOSE_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --verbose */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ VERBOSE_DESC, VERBOSE_NAME, VERBOSE_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 2, VALUE_OPT_INFILE,
     /* equiv idx, value */ 2, VALUE_OPT_INFILE,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ INFILE_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --infile */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptInfile,
     /* desc, NAME, name */ INFILE_DESC, INFILE_NAME, INFILE_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 3, VALUE_OPT_OUTFILE,
     /* equiv idx, value */ 3, VALUE_OPT_OUTFILE,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ OUTFILE_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --outfile */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ OUTFILE_DESC, OUTFILE_NAME, OUTFILE_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 4, VALUE_OPT_LOAD_PUBKEY,
     /* equiv idx, value */ 4, VALUE_OPT_LOAD_PUBKEY,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ LOAD_PUBKEY_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --load-pubkey */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ LOAD_PUBKEY_DESC, LOAD_PUBKEY_NAME, LOAD_PUBKEY_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 5, VALUE_OPT_LOAD_CERTIFICATE,
     /* equiv idx, value */ 5, VALUE_OPT_LOAD_CERTIFICATE,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ LOAD_CERTIFICATE_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --load-certificate */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ LOAD_CERTIFICATE_DESC, LOAD_CERTIFICATE_NAME, LOAD_CERTIFICATE_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 6, VALUE_OPT_DLV,
     /* equiv idx, value */ 6, VALUE_OPT_DLV,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ DLV_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --dlv */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ DLV_DESC, DLV_NAME, DLV_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 7, VALUE_OPT_HASH,
     /* equiv idx, value */ 7, VALUE_OPT_HASH,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ HASH_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --hash */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ HASH_DESC, HASH_NAME, HASH_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 8, VALUE_OPT_CHECK,
     /* equiv idx, value */ 8, VALUE_OPT_CHECK,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ CHECK_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --check */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ CHECK_DESC, CHECK_NAME, CHECK_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 9, VALUE_OPT_CHECK_EE,
     /* equiv idx, value */ 9, VALUE_OPT_CHECK_EE,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ CHECK_EE_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --check-ee */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ CHECK_EE_DESC, CHECK_EE_NAME, CHECK_EE_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 10, VALUE_OPT_CHECK_CA,
     /* equiv idx, value */ 10, VALUE_OPT_CHECK_CA,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ CHECK_CA_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --check-ca */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ CHECK_CA_DESC, CHECK_CA_NAME, CHECK_CA_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 11, VALUE_OPT_INSECURE,
     /* equiv idx, value */ 11, VALUE_OPT_INSECURE,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ INSECURE_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --insecure */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ INSECURE_DESC, INSECURE_NAME, INSECURE_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 12, VALUE_OPT_LOCAL_DNS,
     /* equiv idx, value */ 12, VALUE_OPT_LOCAL_DNS,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ LOCAL_DNS_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --local-dns */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ LOCAL_DNS_DESC, LOCAL_DNS_NAME, LOCAL_DNS_name,
     /* disablement strs */ NOT_LOCAL_DNS_name, NOT_LOCAL_DNS_PFX },

  {  /* entry idx, value */ 13, VALUE_OPT_INDER,
     /* equiv idx, value */ 13, VALUE_OPT_INDER,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ INDER_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --inder */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ INDER_DESC, INDER_NAME, INDER_name,
     /* disablement strs */ NOT_INDER_name, NOT_INDER_PFX },

  {  /* entry idx, value */ 14, VALUE_OPT_INRAW,
     /* equiv idx, value */ 14, VALUE_OPT_INRAW,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ INRAW_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --inraw */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptInraw,
     /* desc, NAME, name */ INRAW_DESC, INRAW_NAME, INRAW_name,
     /* disablement strs */ 0, 0 },

  {  /* entry idx, value */ 15, VALUE_OPT_TLSA_RR,
     /* equiv idx, value */ 15, VALUE_OPT_TLSA_RR,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ TLSA_RR_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --tlsa-rr */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ aTlsa_RrMustList, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ TLSA_RR_DESC, TLSA_RR_NAME, TLSA_RR_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 16, VALUE_OPT_HOST,
     /* equiv idx, value */ 16, VALUE_OPT_HOST,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ HOST_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --host */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ HOST_DESC, HOST_NAME, HOST_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 17, VALUE_OPT_PROTO,
     /* equiv idx, value */ 17, VALUE_OPT_PROTO,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ PROTO_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --proto */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ PROTO_DESC, PROTO_NAME, PROTO_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 18, VALUE_OPT_PORT,
     /* equiv idx, value */ 18, VALUE_OPT_PORT,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ PORT_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --port */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ optionNumericVal,
     /* desc, NAME, name */ PORT_DESC, PORT_NAME, PORT_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 19, VALUE_OPT_CA,
     /* equiv idx, value */ 19, VALUE_OPT_CA,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ CA_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --ca */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ CA_DESC, CA_NAME, CA_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 20, VALUE_OPT_X509,
     /* equiv idx, value */ 20, VALUE_OPT_X509,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ X509_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --x509 */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ X509_DESC, X509_NAME, X509_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 21, VALUE_OPT_LOCAL,
     /* equiv idx, value */ 21, VALUE_OPT_LOCAL,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ LOCAL_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --local */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptLocal,
     /* desc, NAME, name */ LOCAL_DESC, LOCAL_NAME, LOCAL_name,
     /* disablement strs */ 0, 0 },

  {  /* entry idx, value */ 22, VALUE_OPT_DOMAIN,
     /* equiv idx, value */ 22, VALUE_OPT_DOMAIN,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ DOMAIN_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --domain */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ DOMAIN_DESC, DOMAIN_NAME, DOMAIN_name,
     /* disablement strs */ NOT_DOMAIN_name, NOT_DOMAIN_PFX },

  {  /* entry idx, value */ INDEX_OPT_VERSION, VALUE_OPT_VERSION,
     /* equiv idx value  */ NO_EQUIVALENT, VALUE_OPT_VERSION,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ VER_FLAGS, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ VER_PROC,
     /* desc, NAME, name */ VER_DESC, NULL, VER_name,
     /* disablement strs */ NULL, NULL },



  {  /* entry idx, value */ INDEX_OPT_HELP, VALUE_OPT_HELP,
     /* equiv idx value  */ NO_EQUIVALENT, VALUE_OPT_HELP,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ OPTST_IMM | OPTST_NO_INIT, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doUsageOpt,
     /* desc, NAME, name */ HELP_DESC, NULL, HELP_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ INDEX_OPT_MORE_HELP, VALUE_OPT_MORE_HELP,
     /* equiv idx value  */ NO_EQUIVALENT, VALUE_OPT_MORE_HELP,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ MORE_HELP_FLAGS, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL,  NULL,
     /* option proc      */ optionPagedUsage,
     /* desc, NAME, name */ MORE_HELP_DESC, NULL, MORE_HELP_name,
     /* disablement strs */ NULL, NULL }
};


/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 *
 *  Define the danetool Option Environment
 */
#define zPROGNAME       (danetool_opt_strs+2231)
#define zUsageTitle     (danetool_opt_strs+2240)
#define zRcName         NULL
#define apzHomeList     NULL
#define zBugsAddr       (danetool_opt_strs+2340)
#define zExplain        (danetool_opt_strs+2359)
#define zDetail         (danetool_opt_strs+2362)
#define zFullVersion    (danetool_opt_strs+2435)
/* extracted from optcode.tlib near line 350 */

#if defined(ENABLE_NLS)
# define OPTPROC_BASE OPTPROC_TRANSLATE | OPTPROC_NXLAT_OPT
  static tOptionXlateProc translate_option_strings;
#else
# define OPTPROC_BASE OPTPROC_NONE
# define translate_option_strings NULL
#endif /* ENABLE_NLS */


#define danetool_full_usage (NULL)

#define danetool_short_usage (danetool_opt_strs+2451)

#endif /* not defined __doxygen__ */

/*
 *  Create the static procedure(s) declared above.
 */
/**
 * The callout function that invokes the optionUsage function.
 *
 * @param pOptions the AutoOpts option description structure
 * @param pOptDesc the descriptor for the "help" (usage) option.
 * @noreturn
 */
static void
doUsageOpt(tOptions * pOptions, tOptDesc * pOptDesc)
{
    optionUsage(&danetoolOptions, DANETOOL_EXIT_SUCCESS);
    /* NOTREACHED */
    (void)pOptDesc;
    (void)pOptions;
}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/**
 * Code to handle the debug option.
 *
 * @param pOptions the danetool options data structure
 * @param pOptDesc the option descriptor for this option.
 */
static void
doOptDebug(tOptions* pOptions, tOptDesc* pOptDesc)
{
    static struct {long rmin, rmax;} const rng[1] = {
        { 0 ,  9999 } };
    int  ix;

    if (pOptions <= OPTPROC_EMIT_LIMIT)
        goto emit_ranges;
    optionNumericVal(pOptions, pOptDesc);

    for (ix = 0; ix < 1; ix++) {
        if (pOptDesc->optArg.argInt < rng[ix].rmin)
            continue;  /* ranges need not be ordered. */
        if (pOptDesc->optArg.argInt == rng[ix].rmin)
            return;
        if (rng[ix].rmax == LONG_MIN)
            continue;
        if (pOptDesc->optArg.argInt <= rng[ix].rmax)
            return;
    }

    option_usage_fp = stderr;

emit_ranges:

    optionShowRange(pOptions, pOptDesc, (void *)rng, 1);
}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/**
 * Code to handle the infile option.
 *
 * @param pOptions the danetool options data structure
 * @param pOptDesc the option descriptor for this option.
 */
static void
doOptInfile(tOptions* pOptions, tOptDesc* pOptDesc)
{
    static teOptFileType const  type =
        FTYPE_MODE_MUST_EXIST + FTYPE_MODE_NO_OPEN;
    static tuFileMode           mode;
#ifndef O_CLOEXEC
#  define O_CLOEXEC 0
#endif
    mode.file_flags = O_CLOEXEC;

    optionFileCheck(pOptions, pOptDesc, type, mode);
}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/**
 * Code to handle the inraw option.
 *
 * @param pOptions the danetool options data structure
 * @param pOptDesc the option descriptor for this option.
 */
static void
doOptInraw(tOptions* pOptions, tOptDesc* pOptDesc)
{
    int res = optionAlias(pOptions, pOptDesc, INDEX_OPT_INDER);
    if ((res != 0) && ((pOptions->fOptSet & OPTPROC_ERRSTOP) != 0))
        USAGE(DANETOOL_EXIT_FAILURE);

}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/**
 * Code to handle the local option.
 *
 * @param pOptions the danetool options data structure
 * @param pOptDesc the option descriptor for this option.
 */
static void
doOptLocal(tOptions* pOptions, tOptDesc* pOptDesc)
{
    int res = optionAlias(pOptions, pOptDesc, INDEX_OPT_DOMAIN);
    if ((res != 0) && ((pOptions->fOptSet & OPTPROC_ERRSTOP) != 0))
        USAGE(DANETOOL_EXIT_FAILURE);

}
/* extracted from optmain.tlib near line 1113 */

/**
 * The directory containing the data associated with danetool.
 */
#ifndef  PKGDATADIR
# define PKGDATADIR ""
#endif

/**
 * Information about the person or institution that packaged danetool
 * for the current distribution.
 */
#ifndef  WITH_PACKAGER
# define danetool_packager_info NULL
#else
static char const danetool_packager_info[] =
    "Packaged by " WITH_PACKAGER

# ifdef WITH_PACKAGER_VERSION
        " ("WITH_PACKAGER_VERSION")"
# endif

# ifdef WITH_PACKAGER_BUG_REPORTS
    "\nReport danetool bugs to " WITH_PACKAGER_BUG_REPORTS
# endif
    "\n";
#endif
#ifndef __doxygen__

#endif /* __doxygen__ */
/**
 * The option definitions for danetool.  The one structure that
 * binds them all.
 */
tOptions danetoolOptions = {
    OPTIONS_STRUCT_VERSION,
    0, NULL,                    /* original argc + argv    */
    ( OPTPROC_BASE
    + OPTPROC_ERRSTOP
    + OPTPROC_SHORTOPT
    + OPTPROC_LONGOPT
    + OPTPROC_NO_REQ_OPT
    + OPTPROC_NEGATIONS
    + OPTPROC_NO_ARGS
    + OPTPROC_GNUUSAGE
    + OPTPROC_MISUSE ),
    0, NULL,                    /* current option index, current option */
    NULL,         NULL,         zPROGNAME,
    zRcName,      zCopyright,   zLicenseDescrip,
    zFullVersion, apzHomeList,  zUsageTitle,
    zExplain,     zDetail,      optDesc,
    zBugsAddr,                  /* address to send bugs to */
    NULL, NULL,                 /* extensions/saved state  */
    optionUsage, /* usage procedure */
    translate_option_strings,   /* translation procedure */
    /*
     *  Indexes to special options
     */
    { INDEX_OPT_MORE_HELP, /* more-help option index */
      NO_EQUIVALENT, /* save option index */
      NO_EQUIVALENT, /* '-#' option index */
      NO_EQUIVALENT /* index of default opt */
    },
    26 /* full option count */, 23 /* user option count */,
    danetool_full_usage, danetool_short_usage,
    NULL, NULL,
    PKGDATADIR, danetool_packager_info
};

#if ENABLE_NLS
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <autoopts/usage-txt.h>

static char* AO_gettext(char const* pz);
static void  coerce_it(void** s);

/**
 * AutoGen specific wrapper function for gettext.
 * It relies on the macro _() to convert from English to the target
 * language, then strdup-duplicates the result string.
 *
 * @param[in] pz the input text used as a lookup key.
 * @returns the translated text (if there is one),
 *   or the original text (if not).
 */
static char *
AO_gettext(char const* pz)
{
    char* pzRes;
    if (pz == NULL)
        return NULL;
    pzRes = _(pz);
    if (pzRes == pz)
        return pzRes;
    pzRes = strdup(pzRes);
    if (pzRes == NULL) {
        fputs(_("No memory for duping translated strings\n"), stderr);
        exit(DANETOOL_EXIT_FAILURE);
    }
    return pzRes;
}

static void coerce_it(void** s) { *s = AO_gettext(*s);
}

/**
 * Translate all the translatable strings in the danetoolOptions
 * structure defined above.  This is done only once.
 */
static void
translate_option_strings(void)
{
    tOptions * const pOpt = &danetoolOptions;

    /*
     *  Guard against re-translation.  It won't work.  The strings will have
     *  been changed by the first pass through this code.  One shot only.
     */
    if (option_usage_text.field_ct != 0) {
        /*
         *  Do the translations.  The first pointer follows the field count
         *  field.  The field count field is the size of a pointer.
         */
        tOptDesc * pOD = pOpt->pOptDesc;
        char **    ppz = (char**)(void*)&(option_usage_text);
        int        ix  = option_usage_text.field_ct;

        do {
            ppz++;
            *ppz = AO_gettext(*ppz);
        } while (--ix > 0);

        coerce_it((void*)&(pOpt->pzCopyright));
        coerce_it((void*)&(pOpt->pzCopyNotice));
        coerce_it((void*)&(pOpt->pzFullVersion));
        coerce_it((void*)&(pOpt->pzUsageTitle));
        coerce_it((void*)&(pOpt->pzExplain));
        coerce_it((void*)&(pOpt->pzDetail));
        coerce_it((void*)&(pOpt->pzPackager));
        coerce_it((void*)&(pOpt->pzShortUsage));
        option_usage_text.field_ct = 0;

        for (ix = pOpt->optCt; ix > 0; ix--, pOD++)
            coerce_it((void*)&(pOD->pzText));
    }

    if ((pOpt->fOptSet & OPTPROC_NXLAT_OPT_CFG) == 0) {
        tOptDesc * pOD = pOpt->pOptDesc;
        int        ix;

        for (ix = pOpt->optCt; ix > 0; ix--, pOD++) {
            coerce_it((void*)&(pOD->pz_Name));
            coerce_it((void*)&(pOD->pz_DisableName));
            coerce_it((void*)&(pOD->pz_DisablePfx));
        }
        /* prevent re-translation */
        danetoolOptions.fOptSet |= OPTPROC_NXLAT_OPT_CFG | OPTPROC_NXLAT_OPT;
    }
}

#endif /* ENABLE_NLS */

#ifdef  __cplusplus
}
#endif
/* danetool-args.c ends here */
